language: php
php:
- '7.1'
before_install:
- openssl aes-256-cbc -K $encrypted_b137818ae1c7_key -iv $encrypted_b137818ae1c7_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install:
- pecl install mongodb
- phpenv config-add travis_config.ini
- composer install
before_script:
- phpenv config-add travis_config.ini
script: true
after_failure: 
after_success:
after_deploy:
after_script: 
addons:
  ssh_known_hosts: 47.52.153.68

before_deploy:
- openssl aes-256-cbc -K $encrypted_b137818ae1c7_key -iv $encrypted_b137818ae1c7_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa


deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/bin root@47.52.153.68:/tmp
  on:
    branch: master
