language: php
php:
- '7.1'
before_install:
- openssl aes-256-cbc -K $encrypted_b137818ae1c7_key -iv $encrypted_b137818ae1c7_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install:
- pecl install mongodb
- phpenv config-add travis_config.ini
- composer install
before_script:
- phpenv config-add travis_config.ini
script: true
after_failure: 
after_success:
- ssh root@47.52.153.68 'touch /tmp/abc'
after_deploy: 
after_script: 
addons:
  ssh_known_hosts: 47.52.153.68
