language: php

before_install:
- openssl aes-256-cbc -K $encrypted_f6279d9622f9_key -iv $encrypted_f6279d9622f9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 47.52.153.68\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
- composer install
before_script: 
script: true
after_failure: 
after_success:
  -ssh root@47.52.153.68 'cd /data/wwwroot && git pull'
before_deploy: 
after_deploy: 
after_script: 
